name: Soundproofing_Doors_Singapore
favicon: null
layout_spectrum: 0.7518
typography_spectrum: 0.87046
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#6a6255'
    - '#b7a98c'
    - '#938578'
    - '#40362d'
  brandStrength: 0.4129213788546622
  lightness: 0.9929872872307897
  saturation: 0.5602559116668999
  rhythmicContrast: 0.43101743841543794
purpose: []
